[package]
name = "stry-common"
version = "0.1.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

license = "MIT"

[features]
source-clap = [ "clap" ]
with-backend = [ "async-trait" ]
with-io = [ "ron" ]
with-nanoid = [ "rand" ]
with-source-clap = [ "clap" ]
with-source-ron = [ "ron" ]

[dependencies]
async-trait = { version= "0.1", optional = true }
chrono = { version = "0.4", features = [ "serde" ] }
clap = { version = "2.33", default-features = false, optional = true }
miau = { version = "0.1", default-features = false }
rand = { version = "0.7", optional = true }
ron = { version = "0.6", optional = true }
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "1.0"
